site_name: ZhangzrJerry
site_description: "Jerry's personal website"

plugins:  
  - search
  - blog

nav:
  - Home: index.md
  - Resume: resume.md
  - Projects: projects.md
  - Tools: tools/index.md
  - Blogs: blog/index.md
  - Connect: connect.md

theme:
  name: material
  language: en
  custom_dir: overrides
  favicon: img/favicon.ico
  logo: img/favicon.ico
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    - navigation.tracking
    - navigation.sidebar
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.image.lightbox
    - content.card
  language: en

extra_css:
  - stylesheets/index.css
  - stylesheets/blog.css
  - stylesheets/resume.css
  - stylesheets/academics.css
  - stylesheets/neoteroi-v1.0.4.css

extra_javascript:
  - javascripts/index.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - codehilite:
      guess_lang: false  
  - neoteroi.projects
  - neoteroi.timeline

extra:
    social:
        - icon: fontawesome/regular/envelope
          link: https://zzhangje@connect.ust.hk
        # - icon: fontawesome/brands/zhihu
        #   link: https://www.zhihu.com/people/zhang-zi-rui-99-77
        - icon: fontawesome/brands/bilibili
          link: https://space.bilibili.com/504273533
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/zirui-zhang-924958319/
        - icon: fontawesome/brands/orcid
          link: https://orcid.org/0009-0008-4156-1652
        - icon: fontawesome/brands/github
          link: https://github.com/ZhangzrJerry

